[project]
name = "deps"
version = "0.0.0"

[lib]
name = "null"

[dependencies]
libc = "0.1.7"
getopts = "0.2.11"
num_cpus = "*"
rand = "0.3.8"
regex = "0.1.33"
rust-crypto = "0.2.31"
rustc-serialize = "0.3.13"
time = "0.1.25"
unicode-width = "0.1.1"
